In [8]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import json

In [9]:
pathname = os.path.join("watch-history.json")
with open(pathname, "r") as f:
    data = json.load(f)
    df = pd.DataFrame(data)

In [12]:
df.tail()

,header,title,titleUrl,subtitles,time,products,activityControls,description,details
48402,YouTube,Watched Bevis Arealfunktionen er en stamfunk...,https://www.youtube.com/watch?v=PZ8WNNZHmII,"[{'name': 'Annepande', 'url': 'https://www.you...",2020-07-12T20:57:18.686Z,[YouTube],[YouTube watch history],NaN,NaN
48403,YouTube,Watched Tretrinsreglen - Bevis: Differentialkv...,https://www.youtube.com/watch?v=xAYlX_LnQtc,"[{'name': 'KG MAT', 'url': 'https://www.youtub...",2020-07-12T20:51:34.640Z,[YouTube],[YouTube watch history],NaN,NaN
48404,YouTube,Watched https://www.youtube.com/watch?v=19FT6b...,https://www.youtube.com/watch?v=19FT6b9VMTY,NaN,2020-07-12T20:48:08.113Z,[YouTube],[YouTube watch history],NaN,NaN
48405,YouTube,Watched Tame Impala - On Track (Acoustic Live),https://www.youtube.com/watch?v=p3gyCbcB9EY,"[{'name': 'tameimpalaVEVO', 'url': 'https://ww...",2020-07-12T20:46:59.003Z,[YouTube],[YouTube watch history],NaN,NaN
48406,YouTube,Watched Shooting Film Photos on the Mamiya 7II...,https://www.youtube.com/watch?v=OFrqpVdwWeU,"[{'name': 'Willem Verbeeck', 'url': 'https://w...",2020-07-12T19:54:21.179Z,[YouTube],[YouTube watch history],NaN,NaN

In [4]:
# Check how many columns are in the dataframe
df.shape

(48407, 9)

In [5]:
df["subtitles"].value_counts()

subtitles
[{'name': 'theneedledrop', 'url': 'https://www.youtube.com/channel/UCt7fwAhXDy3oNFTAzF2o8Pw'}]             952
[{'name': 'DAZN Boxing', 'url': 'https://www.youtube.com/channel/UCurvRE5fGcdUgCYWgh-BDsg'}]               626
[{'name': 'UFC', 'url': 'https://www.youtube.com/channel/UCvgfXK4nTYKudb0rFR6noLA'}]                       606
[{'name': 'Top Rank Boxing', 'url': 'https://www.youtube.com/channel/UCbzRzJNHx7ZLlJML9BjZQVQ'}]           573
[{'name': 'TMG Podcast Highlights', 'url': 'https://www.youtube.com/channel/UCdftuX9H8kW14Njxtpnuy3Q'}]    302
                                                                                                          ...
[{'name': 'Doctor Gary Linkov', 'url': 'https://www.youtube.com/channel/UCXHS7RSRMGcVp4-MMbEDW6g'}]          1
[{'name': 'Ethan900', 'url': 'https://www.youtube.com/channel/UCzllvrMvKBgq1HjEnVuABTw'}]                    1
[{'name': 'Boxing Ring TV', 'url': 'https://www.youtube.com/channel/UCk2dbyAP4vAS2ecowpbaT0A'}]              1
[{'name': '4k DRIVE TOUR', 'url': 'https://www.youtube.com/channel/UCpp5fMfLI0N-kgVJ7t2b2XA'}]               1
[{'name': 'Dave Taylor', 'url': 'https://www.youtube.com/channel/UCa6UyXhegwV4js_tmhCJrcQ'}]                 1
Name: count, Length: 12487, dtype: int64

In [ ]:
# Remove rows where the details column indicates traffic from Google Ads
df = df[~df["details"].astype(str).str.contains("From Google Ads", na=False)]
df

,header,title,titleUrl,subtitles,time,products,activityControls,description,details
0,YouTube,"Watched Install Git on MacOS (Macbook M1, M1 M...",https://www.youtube.com/watch?v=hMEyBtsuAJE,"[{'name': 'Code With Arjun', 'url': 'https://w...",2024-02-18T15:16:21.549Z,[YouTube],[YouTube watch history],NaN,NaN
1,YouTube,Watched Merab wrestled Bradley Martyn 😂 (via m...,https://www.youtube.com/watch?v=vlzkSH8hHqM,"[{'name': 'ESPN MMA', 'url': 'https://www.yout...",2024-02-18T15:02:17.549Z,[YouTube],[YouTube watch history],NaN,NaN
2,YouTube,Watched 5 Basic Essential Tactics for NOOBS! -...,https://www.youtube.com/watch?v=KMpvjVkfhVo,"[{'name': 'Zerkovich', 'url': 'https://www.you...",2024-02-18T15:01:03.263Z,[YouTube],[YouTube watch history],NaN,NaN
4,YouTube,Watched Skaven Inventions in a Nutshell,https://www.youtube.com/watch?v=pUD9OEp2n3w,"[{'name': 'Tarriff', 'url': 'https://www.youtu...",2024-02-18T15:00:47.482Z,[YouTube],[YouTube watch history],NaN,NaN
6,YouTube,Watched Ilia Topuria says featherweight divisi...,https://www.youtube.com/watch?v=yavn1PQDJzs,"[{'name': 'ESPN MMA', 'url': 'https://www.yout...",2024-02-18T14:53:49.346Z,[YouTube],[YouTube watch history],NaN,NaN
...,...,...,...,...,...,...,...,...,...
48402,YouTube,Watched Bevis Arealfunktionen er en stamfunk...,https://www.youtube.com/watch?v=PZ8WNNZHmII,"[{'name': 'Annepande', 'url': 'https://www.you...",2020-07-12T20:57:18.686Z,[YouTube],[YouTube watch history],NaN,NaN
48403,YouTube,Watched Tretrinsreglen - Bevis: Differentialkv...,https://www.youtube.com/watch?v=xAYlX_LnQtc,"[{'name': 'KG MAT', 'url': 'https://www.youtub...",2020-07-12T20:51:34.640Z,[YouTube],[YouTube watch history],NaN,NaN
48404,YouTube,Watched https://www.youtube.com/watch?v=19FT6b...,https://www.youtube.com/watch?v=19FT6b9VMTY,NaN,2020-07-12T20:48:08.113Z,[YouTube],[YouTube watch history],NaN,NaN
48405,YouTube,Watched Tame Impala - On Track (Acoustic Live),https://www.youtube.com/watch?v=p3gyCbcB9EY,"[{'name': 'tameimpalaVEVO', 'url': 'https://ww...",2020-07-12T20:46:59.003Z,[YouTube],[YouTube watch history],NaN,NaN
48406,YouTube,Watched Shooting Film Photos on the Mamiya 7II...,https://www.youtube.com/watch?v=OFrqpVdwWeU,"[{'name': 'Willem Verbeeck', 'url': 'https://w...",2020-07-12T19:54:21.179Z,[YouTube],[YouTube watch history],NaN,NaN

In [7]:
# Check that no rows with "From Google Ads" remain
df["details"].astype(str).str.contains("From Google Ads", na=False).sum()

0

In [10]:
import json
import random

sample_size = 1000
input_path = "watch-history.json"
output_path = "yt_sample.json"

with open(input_path, "r", encoding="utf-8") as f:
    records = json.load(f)

k = min(sample_size, len(records))
sampled_records = random.sample(records, k=k)

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(sampled_records, f, ensure_ascii=False, indent=2)

print(f"Saved {k} random records to {output_path}")

Saved 1000 random records to yt_sample.json

In [11]:
# load the sample and check it
with open(output_path, "r", encoding="utf-8") as f:
    sample_data = json.load(f)
sample_df = pd.DataFrame(sample_data)
sample_df.head()

,header,title,titleUrl,subtitles,time,products,activityControls,description,details
0,YouTube,Watched Alex Pereira’s left hook destroying fi...,https://www.youtube.com/watch?v=mfj0KCNT2_g,"[{'name': '170 Conor', 'url': 'https://www.you...",2024-02-03T13:55:27.053Z,[YouTube],[YouTube watch history],NaN,NaN
1,YouTube,"Watched Mr. Robot Season 1 Episode 1 ""eps1.0_h...",https://www.youtube.com/watch?v=rTNZTx1G18Y,"[{'name': 'failwhale34', 'url': 'https://www.y...",2021-08-03T14:29:06.864Z,[YouTube],[YouTube watch history],NaN,NaN
2,YouTube,Watched Tyson Fury - The Gypsy King (EXTENDED ...,https://www.youtube.com/watch?v=gTC2vqSCmDs,"[{'name': 'Joseph Vincent', 'url': 'https://ww...",2021-10-18T11:01:01.491Z,[YouTube],[YouTube watch history],NaN,NaN
3,YouTube,Watched but I cum...,https://www.youtube.com/watch?v=EdWlMSTTBSs,"[{'name': 'Tik Davtyan', 'url': 'https://www.y...",2024-01-23T19:52:00.385Z,[YouTube],[YouTube watch history],NaN,NaN
4,YouTube,"Watched ""i'd like to thank god, my family and ...",https://www.youtube.com/watch?v=M8awCYOEeQE,"[{'name': 'TMG Studios', 'url': 'https://www.y...",2023-01-09T15:22:42.005Z,[YouTube],[YouTube watch history],NaN,NaN